name: withdrawal-manager
version: 1.0.1
source: contracts
packages:
  - path: contracts/MapleWithdrawalManager.sol
    contractName: MapleWithdrawalManager
  - path: contracts/MapleWithdrawalManagerFactory.sol
    contractName: MapleWithdrawalManagerFactory
  - path: contracts/MapleWithdrawalManagerInitializer.sol
    contractName: MapleWithdrawalManagerInitializer
customDescription: Withdrawal Manager Artifacts and ABIs
