name: withdrawal-manager
version: 1.0.0-alpha.0
source: contracts
packages:
  - path: contracts/WithdrawalManager.sol
    contractName: WithdrawalManager
  - path: contracts/WithdrawalManagerFactory.sol
    contractName: WithdrawalManagerFactory
  - path: contracts/WithdrawalManagerInitializer.sol
    contractName: WithdrawalManagerInitializer
  - path: contracts/WithdrawalManagerStorage.sol
    contractName: WithdrawalManagerStorage
customDescription: Withdrawal Manager Artifacts and ABIs
