name: withdrawal-manager
version: 1.0.0
source: contracts
packages:
  - path: contracts/WithdrawalManager.sol
    contractName: WithdrawalManager
  - path: contracts/WithdrawalManagerFactory.sol
    contractName: WithdrawalManagerFactory
  - path: contracts/WithdrawalManagerInitializer.sol
    contractName: WithdrawalManagerInitializer
customDescription: Withdrawal Manager Artifacts and ABIs
